export const ADD_BLOG = 'ADD_BLOG';
export const EDIT_BLOG = 'EDIT_BLOG';
export const DELETE_BLOG = 'DELETE_BLOG';
export const TOGGLE_EDIT_MODAL = 'TOGGLE_EDIT_MODAL';

export const LOAD_BLOGS_START = 'LOAD_BLOGS_START';
export const LOAD_BLOGS_END = 'LOAD_BLOGS_END';
export const LOAD_BLOGS_SUCCESS = 'LOAD_BLOGS_SUCCESS';
export const LOAD_BLOGS_FAILURE = 'LOAD_BLOGS_FAILURE';