export const LOAD_COMMENTS_START = 'LOAD_COMMENTS_START';
export const LOAD_COMMENTS_END = 'LOAD_COMMENTS_END';
export const LOAD_COMMENTS_SUCCESS = 'LOAD_COMMENTS_SUCCESS';
export const LOAD_COMMENTS_FAILURE = 'LOAD_COMMENTS_FAILURE';

export const LOAD_ALL_COMMENTS_START = 'LOAD_ALL_COMMENTS_START';
export const LOAD_ALL_COMMENTS_END = 'LOAD_ALL_COMMENTS_END';
export const LOAD_ALL_COMMENTS_SUCCESS = 'LOAD_ALL_COMMENTS_SUCCESS';
export const LOAD_ALL_COMMENTS_FAILURE = 'LOAD_ALL_COMMENTS_FAILURE';